name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: atactions/fork-sync@v1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}         
